image: golang
workspace: /go/src/github.com/wercker/getting-started-golang
env:
  - name: USER
    valueFrom:
      secretKeyRef:
        name: prod-db-secret
        key: username
  - name: PASSWORD
    valueFrom:
      secretKeyRef:
        name: prod-db-secret
        key: password
checkout:
  url: https://github.com/wercker/getting-started-golang.git
run:
  command:
    - bash
    - "-exc"
  args:
    - echo $(USER); echo $(PASSWORD)
